version: '3.7'
services:
  app:
    stdin_open: true
    image: docker.pkg.github.com/fga-eps-mds/2020.1-minacademy-frontend/app:production
    ports:
      - '3000:3000'
    networks:
      - client-server-network
    environment: 
      REACT_APP_SERVER_URL: http://167.99.163.1:9000

networks:
  client-server-network:
    external:
      name: client-server-network